### ISSUE TITLE
Information on adding Host Key / Passphrase is missing

### ISSUE THREAD

**Issue by zafar-saleem** [SublimeGit/SublimeGit#123]
After reading and searched through documentation, information on adding Host Key / Passphrase is not available. I am trying to pull and push from my remote repository and keep getting this error 

Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

When I pull and push from command line everything works smoothly but not in sublimegit.

**Comment by michaelpedersen** [comment]
There is documentation here: https://docs.sublimegit.net/quickstart.html#git-configuration as well as user submitted documentation here: https://docs.sublimegit.net/troubleshooting.html#remote-issues
