### ISSUE TITLE
Vintageous mode

### ISSUE THREAD

**Issue by leemhenson** [SublimeGit/SublimeGit#125]
So, it looks like this issue:

https://github.com/SublimeGit/SublimeGit/issues/120

now prevents me (a Vintageous user) from doing things like ```:10``` to jump to a specific line in the git-status page if I want to stage/unstage a particular file. It looks like I need to use the cursor keys/pointer to get to that line, which is pretty slow. Is there any way we can make git-status disabling of Vintageous an optional thing?

**Comment by michaelpedersen** [comment]
Well this kinda leaves us stuck between a rock and a hard place. What would your suggested fix be, taking into account that from SublimeGit's side it's more a less an all-or-nothing decision to allow or disallow vintageous mode?

**Comment by miquella** [comment]
Would it be possible to go halfway and have a setting that allows Vintageous behaviors, but otherwise disables it?

**Comment by michaelpedersen** [comment]
That's my current thinking on it. Something like a `git_disable_vintageous` settings which defaults to `true` should do it trick. Then power users can just flip it.

**Comment by miquella** [comment]
Sounds great!

**Comment by michaelpedersen** [comment]
Just released 1.0.34 which introduces this setting. See the default settings file.

**Comment by leemhenson** [comment]
:beers:
