### ISSUE TITLE
Slow Performance on Windows (git scm 1.9.2)

### ISSUE THREAD

**Issue by altembo** [SublimeGit/SublimeGit#137]
Hi there,

im on Windows 7 x64 (Core i7, 8GB Ram, 256GB SSD) with SublimeText 2 and SublimeGit 1.0.32 and every action within git-status takes at least 2 seconds.

for example:
- staging one file: ~2 seconds
- unstaging many files: ~3-4 seconds

So without deactivating "git_update_status_on_focus" I would not be able to use it at all.

Is there any known Issue or even a workaround? The only thing I mentioned is, that every git-status call by SublimeGit eats 25% of my CPU (git.exe) for finishing this operation. Doing the same inside git-bash (outside sublime) is fast as always.

Kind Regards,
Al

**Comment by michaelpedersen** [comment]
Since this seems to be a bug in msysgit, i'm gonna close it here.

**Comment by bobojo** [comment]
I'm also getting insane slowdown when I view any Git: Status window on my Windows 7 machine. I'm not using msysgit, and running `git stash list` or `git status` from the command line gives me nearly instant results. SublimeGit may be using a different version of git from command line, so I'll investigate that possibility, but so far it seems like it just doesn't matter how I have git installed or configured in ST3.
