### ISSUE TITLE
Push/Pull Freeze on Windows

### ISSUE THREAD

**Issue by henrymei** [SublimeGit/SublimeGit#15]
The problem I experienced trying to get SublimeGit/ST2 to run on Windows was that any remote git call caused ST2 to lock up and freeze. This seems to be a known issue, and the problem is caused by Git requiring the ssh passphrase for any push/pull operation. The documentation points [here](https://help.github.com/articles/working-with-ssh-key-passphrases), which uses ssh-agent to store credentials. This allows Git Bash to only ask for the passphrase on first run and not any time after. However, I still experienced the same issue.

**Comment by nathanhere** [comment]
Thanks for the tip @albertosantini. What a great integration into the windows workflow! For some reason I just needed an extra backslash after _'%USERPROFILE%_:

C:\My\Path\pageant.exe %USERPROFILE%**\**.ssh\id_rsa.ppk -c C:\My\AnotherPath\SublimeText\sublime_text.exe
