### ISSUE TITLE
Git Pull Not Working in ST3 on Yosemite

### ISSUE THREAD

**Issue by garand** [SublimeGit/SublimeGit#150]
Running `git pull` in SublimeGit in Sublime Text 3 on Yosemite throws this error:

`/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-pull: line 11: git-sh-setup: No such file or directory`

Other commands, such as `git push`, work as expected.

**Comment by michaelpedersen** [comment]
I've just released v1.0.33, which tries to address this issue. Please let me know if it's working.

**Comment by garand** [comment]
Works here. :ok_hand:

**Comment by renolc** [comment]
Pulling and stashes now work for me, with no further alternations having to be made. :+1:

**Comment by bmounteer** [comment]
Working here.


Bill Mounteer


Web Developer

 

Lendio, Inc.

10235 South Jordan Gateway, Suite 410

South Jordan, Utah 84095




Phone: 801.850.2562 

Web: www.lendio.com

**Comment by skotzko** [comment]
Working for me also. Nice job! :+1:

**Comment by rudeworks** [comment]
Fixed here too! :+1:

**Comment by noon-ehos** [comment]
Yes, nice long-long job! :)

**Comment by jbrooksuk** [comment]
Working here too.

**Comment by morinap** [comment]
:+1:

**Comment by bobbyrenwick** [comment]
Working :+1:

**Comment by michaelpedersen** [comment]
Closing this, since it seems to be working for everyone.

**Comment by protej** [comment]
No, unfortunately not for me:
`/Library/Developer/CommandLineTools/usr/libexec/git-core/git-pull: line 11: git-sh-setup: No such file or directory`
Yosemite 10.10.2 (14C109) + ST3 + SublimeGit 1.0.34

**Comment by garand** [comment]
@protej Did you restart Sublime/your computer? I had to do that on one of my machines.

**Comment by protej** [comment]
ouch.. Yes, now I did, and it works! Thanks!

**Comment by yetithefoot** [comment]
What works for me! I specified ```git_force_path``` option in user's SublimeGit.sublime-settings file.

It looks like that:
```json
{
"git_force_path": ["/Library/Developer/CommandLineTools/usr/libexec/git-core/:/usr/bin:/bin"]
}
```
