### ISSUE TITLE
Can't commit from git-diff view

### ISSUE THREAD

**Issue by cloudhead** [SublimeGit/SublimeGit#157]
Pressing 'c' from the diff view doesn't work. I tried creating a custom keybinding too but that doesn't seem to work either. I'm using Vintage mode, so that could be the issue, but I tried various different keybindings.

**Comment by michaelpedersen** [comment]
You're not supposed to be able to commit directly from the diff view. You should be able to stage and unstage hunks with `s` and `u` respectively though.
