### ISSUE TITLE
Ability to show diff without whitespace changes

### ISSUE THREAD

**Issue by umurgdk** [SublimeGit/SublimeGit#17]
There is an '-b' option for git diff. It's extremely useful when you are fixing code formatting. With this option you can easily notice the actual different without whitespace refactoring.

**Comment by forsethc** [comment]
+1 here

**Comment by molecular** [comment]
when in diff view, how do I activate a "shortcut toggle"? I can't find this.

can't we just have -b, -w as config options in settings? I'd also love to see whitespace ignored in status view
