### ISSUE TITLE
Solution for "Git Pull Not Working in ST3 on Yosemite"

### ISSUE THREAD

**Issue by binhwpo** [SublimeGit/SublimeGit#171]
Hi everyone,

I'm facing the same issue with this. https://github.com/SublimeGit/SublimeGit/issues/150

I know you guys are working on this. I tried myself using `Git` plugins (which has custom git path). It yield the same problem with SublimeGit, but on the `/usr/local/git/libexec/git-core`. So I tried by modifying all the files inside `/usr/local/git/libexec/git-core` to find out that actually the `.` as relative path is not working.

After reading this thread I confirm that this is not a bug related to SublimeGit as an app but Yosemite as a whole: http://tex.stackexchange.com/questions/208181/why-did-my-tex-related-gui-program-stop-working-in-mac-os-x-yosemite

**What I tried to get it WORK: Run Sublime Text directly from Terminal:**

`/Applications/Sublime\ Text.app/Contents/MacOS/Sublime\ Text`

If you guys can make a bug fix, that's great. Otherwise, I guess better off leaving this for Git or Apple to handle on next update.

Cheers,
Binh

**Comment by asfaltboy** [comment]
@noon-ehos The `git` binary reportedly used by Sublime Text in your screenshot is from `/usr/local/Cellar/git`, I guess you have to add the related path `/usr/local/Cellar/git/libexec/git-core` in order for the helper scripts to be found (that worked for me). Woohoo and my stash list is displayed in git-status again, thanks @binhwpo  :+1:

**Comment by binhwpo** [comment]
@asfaltboy Thanks for sharing that. And thanks for the thumbup. I'm very glad this helped someone.

**Comment by jerryf196** [comment]
Good work but we shouldn't be busting our heads for a plugin that is not 100% free!!!!

**Comment by michaelpedersen** [comment]
I've just released v1.0.33, which tries to address this issue. It includes a fix which seems to work, but just in case it doesn't there's also a setting called `git_force_path` that allows for setting a specific path used when calling git.

Please test it out, and let me know if it works.

Also, @jerryf196, you're more than welcome to sit down and write one, or go contribute to the free one. No one is forcing you to use this project (or even pay for it!)

**Comment by jerryf196** [comment]
Of course I am welcome to write my own and not pay for it. But as you see people (paid & not paid) are actually creating issues for this since Aug 2014? 

Speaking about the free one. They had the same issue and fixed it right away! I am glad you fixed it and it's a great sublime plugin which was a pitty to see so many users struggling for the same issue.

**Comment by michaelpedersen** [comment]
@jerryf196 In a way i can thank you, because it was kinda your comment that pushed me over the edge to get the fix out there.

**Comment by binhwpo** [comment]
@michaelpedersen I'm very glad that you fixed it. This plugin does have some limitations, but so far this is still the best git plugin... Thank you very much!

**Comment by kopurando** [comment]
crazy... just spent 2+ hrs on google trying to track this issue down (and find a fix for it)... My I just leave some error messages, so people can find this page faster:

Some hooks can't find python:

```
env: python: No such file or directory
```
Git pull broken:
```
/usr/local/git/libexec/git-core/git-sh-setup: line 83: basename: command not found
/usr/local/git/libexec/git-core/git-sh-setup: line 83: sed: command not found
/usr/local/git/libexec/git-core/git-sh-setup: line 299: uname: command not found
/usr/local/git/libexec/git-core/git-pull: line 285: sed: command not found
/usr/local/git/libexec/git-core/git-pull: line 285: tr: command not found
```

How to fix:
In sublimegit user preferences:

```
   "git_force_path": "/usr/local/git/libexec/git-core:/usr/local/git/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"}
```
