### ISSUE TITLE
Sublimegit produces "no branch" / detached head states

### ISSUE THREAD

**Issue by maxheld83** [SublimeGit/SublimeGit#174]
I can't reliably reproduce this error, but since using Sublimegit (in a setup with nested submodules), I seem to find myself with a lot of `no branch` situations, where I do some work in a submodule and find that it has lost its branch.
Needness to say, that easily leads to "detached head" states, or even lost work.

Any thoughts on this?

I'll try to narrow down the conditions to reproduce this.

**Comment by miped** [comment]
A git clone with submodules will by default produce detached head states. This is part of how submodules work (and why they're so confusing). SublimeGit has no special handling for submodules, it just sees another repo (which it is), that happens to be nested inside of a bigger repo.
