### ISSUE TITLE
Git Pull Not Working in ST3 on Yosemite 

### ISSUE THREAD

**Issue by noon-ehos** [SublimeGit/SublimeGit#175]
Issue #150 opened on Aug 4, 2014
Not fixed Yet! 
All office waiting for it! Man!

**Comment by ClleaR** [comment]
+1

**Comment by ZherebcovSergey** [comment]
Yep!

**Comment by noon-ehos** [comment]
If you need some help with OS X platform testing i can do that. Or use teamviewer with me, but please fix it!

**Comment by max-mykhailenko** [comment]
Why it doesn't work!?

**Comment by Suhov-Igor** [comment]
I also want to use it, pls fix this!

**Comment by max-mykhailenko** [comment]
Why contributor @michaelpedersen ignore so many issues and so important like this?

**Comment by jerryf196** [comment]
What is funny is that an alert popups up once in awhile requesting us to pay! YEAH RIGHT I am not paying for this great support!

**Comment by Alanaktion** [comment]
I _did_ pay for it, and regret it almost daily. It's the most unstable, poorly supported software I've used in a while. Just use the open source "Git" package from Package Control, it's open source, much more stable, and has most of the same features. And it works perfectly on Yosemite.

**Comment by jerryf196** [comment]
Yes i tried the open source Git and works. I am jumping back to brackets.io which has at 100% free git plugin with a GUI

**Comment by michaelpedersen** [comment]
First off, thank you for creating a new issue just to vent. It's very helpful.

@Alanaktion I'm sorry that it has apparently caused you a limitless amount of regret. As for the "unstable" part, I've failed to find the bug you've filed for that?

I've just released v1.0.33, which tries to address this issue. Please let me know if it's working.

**Comment by max-mykhailenko** [comment]
bug...
```
/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-pull: line 11: git-sh-setup: No such file or directory
```

**Comment by noon-ehos** [comment]
Now work! Thanks. Work only with "git_force_path": ["/usr/local/bin", "/usr/bin", "/bin"] in user settings. And Restart Sublime!!! 
My Conf:
SublimeGit v1.0.33,
git version 2.2.2 (from brew)
OS X Yosemite (Latest update)

**Comment by max-mykhailenko** [comment]
If I left only
`/usr/local/bin`
I have this
```
/usr/local/Cellar/git/2.2.2/libexec/git-core/git-sh-setup: line 83: basename: command not found
/usr/local/Cellar/git/2.2.2/libexec/git-core/git-sh-setup: line 83: sed: command not found
/usr/local/Cellar/git/2.2.2/libexec/git-core/git-sh-setup: line 299: uname: command not found
error: cannot run ssh: No such file or directory
fatal: unable to fork
```

With `/usr/bin` works fine.
