### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by Zachu** [SublimeGit/SublimeGit#179]
The SSL certificate for *.sublimegit.net expired on 2015-02-012 and I guess that's what's preventing installations from PackageControl also. Install package doesn't see the SublimeGit there and https://packagecontrol.io/packages/SublimeGit says ```Package info was unavailable last time crawler ran. Error downloading repository. HTTP exception InvalidCertificateException (Host release.sublimegit.net returned an invalid certificate ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:547))) downloading https://release.sublimegit.net/packages.json.```. Oh and of course the website is showing red on the url bar because of invalid certificate.

Thanks for fixing, just thought you'd know ;) (Although you might notice it sooner yourself)

**Comment by michaelpedersen** [comment]
Woops... fixing it now.
