### ISSUE TITLE
Please consider storing licence information in a separate file

### ISSUE THREAD

**Issue by N4M3Z** [SublimeGit/SublimeGit#184]
Please consider storing licence information in a separate file like SublimeGit.sublime-license (the way Sublimerge package does it). This would allow users to share settings while keeping only the license file protected (or better yet, encrypted via blackbox or vice versa).

**Comment by Lindenk** [comment]
+1. It's pretty frustrating to have to specifically exclude the settings for this plugin when committing my dotfiles to github.

**Comment by ultrafez** [comment]
Is this still relevant now that SublimeGit is open source?

**Comment by miped** [comment]
Not relevant anymore.
