### ISSUE TITLE
ambigious to select right command

### ISSUE THREAD

**Issue by KES777** [SublimeGit/SublimeGit#187]
1. If you install Git and 'SublimeGit'
2. Go to command: CTRL+SHIFT+P
3. and type: git status

you get two identical command appearance.

Please add some gray text after command to allow me to see to which package command belongs.
like SideBarGit does.
Thank you.

**Comment by miped** [comment]
Honestly, you should probably be using one or the other. Using both is just gonna get super confusing no matter what you do.

**Comment by KES777** [comment]
In any case please consider the SideBarGit behavior
