### ISSUE TITLE
Git-flow executable missing

### ISSUE THREAD

**Issue by mikk150** [SublimeGit/SublimeGit#205]
Git-flow section tells me that git-flow executable is missing
```
Executable '['git-flow']' was not found in PATH. Current PATH:
```
altough I have git-flow installed(but it isn't found as git-flow it is actually "git flow"

```
$ git flow version
1.8.0 (AVH Edition)
```
I have tried to change user settings, but it doesn't do anything
```
{
    "email": "xxxxx@xxxxxxx.xx",
    "product_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",

    "git_executables": {
        "git": ["git"],
        "git_flow": ["git flow"],
        "legit": ["legit"],
        "gitk": ["gitk"]
    }
}

```

**Comment by domibarton** [comment]
Have you tried to use this notation:

```yaml
        "git_flow": ["git", "flow"],
```

**Comment by mikk150** [comment]
yes, works!
I don't know why i didn't tought about that

**Comment by domibarton** [comment]
awesome :+1: :)

can you close the bug to support @miped in his work? ;)
