### ISSUE TITLE
Getting 0 changed files using CodeKit and ST3.

### ISSUE THREAD

**Issue by joshuaiz** [SublimeGit/SublimeGit#207]
I'm getting 0 changed files with several local repos using CodeKit and ST3. I can verify that CodeKit is preprocessing the files (.scss -> .css) and the files are being updated.

Somehow, SublimeGit is not seeing the changes.

I tried deleting my local repo and reinitializing it but still getting "0 changes". Any ideas on how to fix this?

**Comment by domibarton** [comment]
Can you see the changes when you're running a `git status` on the command line?

**Comment by joshuaiz** [comment]
I deleted and reinitialized my local repo again and that solved this.

**Comment by domibarton** [comment]
OK thanks for the reply!
Can you close the issue? :)
