### ISSUE TITLE
Annotate changed lines

### ISSUE THREAD

**Issue by danfare** [SublimeGit/SublimeGit#212]
Please add the ability to annotate lines that have changed since the last commit. A similar feature is in this library: https://github.com/kemayo/sublime-text-git/blob/master/annotate.py

The functionality between this package and that one is very similar so I am hoping it can be added relatively painless.

**Comment by miped** [comment]
Please see issue #27 for a discussion of this. There's no reason to duplicate functionality, when the projects work perfectly fine in unison.
