### ISSUE TITLE
Console does not handle EOL correctly during git push

### ISSUE THREAD

**Issue by m-sostero** [SublimeGit/SublimeGit#221]
The console showing the status during `git push` doesn't seem to handle end-of-line characters correctly (on Windows, at least).
The status is show on the same line and displays a `[CR]` (carriage return) character.
Changing the EOL settings for the current pane doesn't affect this.
![immagine](https://cloud.githubusercontent.com/assets/9999740/16276566/33e175d2-38af-11e6-9fa8-d2f37c808fa3.png)

**Comment by miped** [comment]
Could you run `git config --list` from within the repository, and paste the output? Be sure to remove anything sensitive.

**Comment by m-sostero** [comment]
Sure! TThese should be the relevant settingss
```
core.autocrlf=true
core.bare=false
core.filemode=false
core.fscache=true
core.hidedotfiles=dotGitOnly
core.ignorecase=true
core.logallrefupdates=true
core.pager=less
core.repositoryformatversion=0
core.safecrlf=false
core.symlinks=false
diff.astextplain.textconv=astextplain
gui.encoding=utf-8
help.format=html
rebase.autosquash=true
```

**Comment by miped** [comment]
A couple more things: Windows version? ST version? SublimeGit version? And could you run `chcp` in terminal.exe to get the code page that your system is running?

**Comment by m-sostero** [comment]
I'm sorry, I got confused, I got this while running [kemayo/sublime-text-git](https://github.com/kemayo/sublime-text-git). 
Sorry!
