### ISSUE TITLE
"S" : Stag all unstaged files, doesn't work

### ISSUE THREAD

**Issue by mittalyashu** [SublimeGit/SublimeGit#252]
"S": Stag all unstaged files, doesn't work

![image](https://user-images.githubusercontent.com/29014463/31838927-80f40954-b5fc-11e7-8a7b-98feb63b3b3b.png)

**Comment by mmattes** [comment]
Works fine for me. Can you may provide more details?

**Comment by mittalyashu** [comment]
I work for mine too. 
Actually, my keyword was changed to some other language, that's why it didn't work.

*Sorry for creating this issue.*
