### ISSUE TITLE
<Bug> Unstage running `git rm` instead of `git reset`

### ISSUE THREAD

**Issue by weelillad** [SublimeGit/SublimeGit#256]
Usually when I want to unstage a file, I intend to restore the file to its last committed state, which is what `git reset` does. Instead SublimeGit is running `git rm`, which deletes the file. 

If this is indeed the intended behavior, can there be another shortcut provided to reset the file?

**Comment by mmattes** [comment]
Are you sure that this is happening? According to the code `git rm` is only done if the file is new and never commited.

```
 def unstage(self, repo, files):
        if self.no_commits(repo):
            return self.git(['rm', '--cached', '--'] + files, cwd=repo)
        return self.git(['reset', '-q', 'HEAD', '--'] + files, cwd=repo)
```

May you can specify what you are doing exactly step by step?

**Comment by weelillad** [comment]
Yup, sorry, I seem to have misinterpreted the behavior. The actual issue is this:

1. From a clean checkout, I make changes to multiple files (say, a.js and b.js). In the *git-status* dialog, I press `s` to stage both of the files. Now, my *git-status* displays only:
```
Staged changes:
    a.js
    b.js
```

2. I decide that I don't want any of those changes. I move my cursor to the `Staged changes:` line and press `u`. Now, I am expecting my git-status to display:
```
Nothing to commit (working directory clean)
```
Instead it displays:
```
Untracked files:
    a.js
    b.js
    <and all other files in my repository>

Staged changes:
    Deleted    a.js
    Deleted    b.js
    Deleted    <all other files in my repository>
```
So that's where I concluded that SublimeGit is running `git rm` instead of `git reset` when unstaging.

I think the key might be that I'm trying to unstage the entire `Staged changes` section at once, rather than file by file.

**Comment by mmattes** [comment]
If I'm right then the backspace command should do what you have been expecting as it removes any made changes

**Comment by weelillad** [comment]
Referring to the [Git book](https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things), I would expect `u` to be the equivalent of unstaging a staged file and `backspace` to be unmodifying a modified file. `u` works exactly as expected for single files, but not when used on the entire staged section, where it is instead doing `git rm -r *` .

**Comment by mmattes** [comment]
I think we need to see the two things seperately here. 

First of all i would not say that `backspace = discard file/section` should be renamed to unmodifying as this command does a lot more then just unmodifying files like they are listed in the Git book. This command does clean, checkout and reset depending on the status of the file/selection. 

Also I cant confirm that `U` on the entire staged section is doing `git rm -r *` according to the code it is doing `git rm -r --cached .` in case there has not been any commit yet to the repro at all and `git reset -q HEAD` when there is already a commit. For me this is all correct and working fine.

**Comment by weelillad** [comment]
Ok, it might be my own misunderstanding. Thanks for taking a look at this issue.
