### ISSUE TITLE
Executable '['git']' was not found in PATH

### ISSUE THREAD

**Issue by ghost** [SublimeGit/SublimeGit#55]
Every time I launch Sublime with this package installed I get this error message. 

Executable '['git']' was not found in PATH. Current PATH:

/usr/local/git/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/bin
/Users/rt/bin

Try adjusting the git_executables['git'] setting.

The package works fine however.

On OSX 10.8.5 my git is located in /usr/local/git/bin/git. Verified this by "which git" on the command line and "/usr/local/git/bin/git --version"

Added the absolute path to both the user level and package level preference file:

"git_executables": {
        "git": ["/usr/local/git/bin/git"],
        "git_flow": ["git-flow"],
        "legit": ["legit"],
        "gitk": ["gitk"]
    },

Added path to .profile, .bash_profile:

export PATH="/usr/local/git/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:$PATH"

Added the path to /etc/launchd.conf:

setenv PATH /usr/local/git/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

The error message even shows that Sublime knows the location of the correct path. 

So why the error???

**Comment by johnnybenson** [comment]
This fixed it for me: https://github.com/int3h/SublimeFixMacPath

Not sure how sustainable a solution, but it gives Sublime access to the PATH values set in my .bash_profile

So sublime has access to anything installed with Brew etc.

**Comment by dustinrjo** [comment]
@johnnybenson Like a boss!

**Comment by marsjaninzmarsa** [comment]
LMDE Betsy (based on Debian Jessie), ST3083, unmodified package from package manager, same issue.

**Comment by anhdat** [comment]
SublimeGit is seemed to like `/usr/local/bin` first. Fixed by creating symbolic links to `/usr/local/bin`:

```bash
cd /usr/local/bin
ln -s /usr/bin/git ./
ln -s /usr/bin/git-flow ./
ln -s /usr/bin/legit ./
ln -s /usr/bin/gitk ./
```

SublimeText3 on Arch Linux

**Comment by brybrant** [comment]
I had this same issue and none of the above solutions worked for me. I use [Cygwin](https://www.cygwin.com/) on Windows 10 and I found this fixed the problem for me:

(Sublime Text 3) Preferences -> Package Settings -> SublimeGit -> Settings — User
```
{
  "git_executables": {
    "git": ["C:\\cygwin64\\bin\\git.exe"]
  }
}
