### ISSUE TITLE
Custom commands issue with pulling

### ISSUE THREAD

**Issue by baldurpan** [SublimeGit/SublimeGit#75]
It seems like SublimeGit will not read remotes other than origin.
I tried setting up a custom command like this:

```javascript
{
        "caption": "Git: Pull home",
        "command": "git_custom",
        "args": {
            "cmd": "pull home development",
            "output": "panel",
            "async": true
        }
}
```

In this case, I usually just type in "git pull home development" in the shell and it works fine.
But I get this error when running the custom command in ST3:

```
fatal: 'home' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists. 
```

It seems to work just fine when I change the args to "pull origin development".

**Comment by michaelpedersen** [comment]
Pretty sure it was a case of the commands file not being live updated :-) Sometimes it takes a restart for changes to get picked up properly.
